import { useState } from "react";
import { Link } from "wouter";
import { useAuth, authHeaders } from "@/lib/auth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { Lock, Search, Save, ArrowLeft, Plus, Upload, Trash2 } from "lucide-react";

const fields = [
  ["first_name","First Name"],["last_name","Last Name"],["email","Email"],["phone","Phone"],["nationality","Nationality"],["date_of_birth","Date of Birth"],["passport_number","Passport Number"],["passport_expiry","Passport Expiry"],["current_address","Current Address"],["permit_type","Permit Type"],["job_salary","Job Salary"],["employer_name","Employer Name"],["employer_country","Employer Country"],["job_title","Job / Position"],["start_date","Start Date"],["contract_duration","Contract Duration"]
] as const;
const statuses = ["pending_payment","submitted","payment_confirmed","approved","rejected","under_review"];
const payments = ["unpaid","pending","paid","rejected"];

function fileToDataUrl(file: File): Promise<string> { return new Promise((resolve,reject)=>{ const r=new FileReader(); r.onload=()=>resolve(String(r.result)); r.onerror=reject; r.readAsDataURL(file); }); }

export default function AdminFileSearch() {
  const { user, isAdmin } = useAuth(); const { toast } = useToast();
  const [ref,setRef]=useState(""); const [app,setApp]=useState<any>(null); const [loading,setLoading]=useState(false); const [saving,setSaving]=useState(false); const [creating,setCreating]=useState(false); const [newFile,setNewFile]=useState<any>(blank());
  async function search(){ if(!user||!ref.trim())return; setLoading(true); try{const r=await fetch(`/api/admin/file-search/${encodeURIComponent(ref.trim().toUpperCase())}`,{headers:authHeaders(user.token)});const d=await r.json();if(!r.ok)throw new Error(d.error);setApp(d.application);}catch(e){setApp(null);toast({title:"Not found",description:e instanceof Error?e.message:"Application not found",variant:"destructive"});}finally{setLoading(false);} }
  async function upload(target:any,key:string,file?:File){if(!file)return;if(file.size>2_500_000){toast({title:"File too large",description:"Please use a file under 2.5 MB.",variant:"destructive"});return;}try{const v=await fileToDataUrl(file);setApp({...target,[key]:v});}catch{toast({title:"Upload failed",variant:"destructive"});}}
  async function save(){if(!user||!app)return;setSaving(true);try{const endpoint=`/api/admin/file-search/${app.id}`;const r=await fetch(endpoint,{method:"PATCH",headers:{"Content-Type":"application/json",...authHeaders(user.token)},body:JSON.stringify(toPayload(app))});const d=await r.json();if(!r.ok)throw new Error(d.error);setApp(d.application);toast({title:"Saved",description:"File updated successfully."});}catch(e){toast({title:"Error",description:e instanceof Error?e.message:"Could not save",variant:"destructive"});}finally{setSaving(false);}}
  async function remove(){if(!user||!app||!window.confirm("Delete this file? You can create it again later with the same File Number."))return;try{const endpoint=app.source_type==="application"?`/api/admin/file-search/application/${app.id}`:`/api/admin/file-search/${app.id}`;const r=await fetch(endpoint,{method:"DELETE",headers:authHeaders(user.token)});const d=await r.json();if(!r.ok)throw new Error(d.error);setApp(null);setRef("");toast({title:"File deleted",description:"You can now create a new file with the same File Number."});}catch(e){toast({title:"Delete failed",description:e instanceof Error?e.message:"Could not delete file",variant:"destructive"});}}
  async function create(){if(!user)return;setCreating(true);try{const r=await fetch(`/api/admin/file-search`,{method:"POST",headers:{"Content-Type":"application/json",...authHeaders(user.token)},body:JSON.stringify(toPayload(newFile,true))});const d=await r.json();if(!r.ok)throw new Error(d.error);setApp(d.application);setRef(d.application.reference_number);toast({title:"File created",description:`File Number: ${d.application.reference_number}`});}catch(e){toast({title:"Error",description:e instanceof Error?e.message:"Could not create file",variant:"destructive"});}finally{setCreating(false);}}
  if(!isAdmin)return <div className="min-h-screen flex items-center justify-center"><div className="text-center"><Lock className="mx-auto mb-3"/><p>Admin Access Required</p><Button asChild className="mt-4"><Link href="/admin/login">Admin Login</Link></Button></div></div>;
  return <div className="min-h-screen bg-muted/20 p-4 md:p-8"><div className="max-w-5xl mx-auto"><div className="flex flex-wrap items-center gap-3 mb-6"><Button asChild variant="outline" size="sm"><Link href="/admin"><ArrowLeft className="w-4 h-4 mr-1"/>Admin</Link></Button><h1 className="text-2xl font-bold text-primary">File Number Search</h1><Button variant="secondary" className="ml-auto" onClick={()=>{setApp(null);setNewFile(blank());setRef("")}}><Plus className="w-4 h-4 mr-1"/>New File</Button></div>
    <div className="bg-card border rounded-xl p-5"><div className="flex gap-2"><Input value={ref} onChange={e=>setRef(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void search();}} placeholder="Search File Number / Reference Number"/><Button onClick={search} disabled={loading}><Search className="w-4 h-4 mr-2"/>{loading?"Searching...":"Search"}</Button></div></div>
    {app ? <Editor app={app} setApp={setApp} upload={upload} save={save} remove={remove} saving={saving}/> : <Editor app={newFile} setApp={setNewFile} upload={upload} save={create} saving={creating} createMode/>}
  </div></div>;
}
function Editor({app,setApp,upload,save,remove,saving,createMode=false}:{app:any;setApp:(v:any)=>void;upload:(target:any,key:string,file?:File)=>Promise<void>;save:()=>Promise<void>;remove?:()=>Promise<void>|void;saving:boolean;createMode?:boolean}){
 return <div className="bg-card border rounded-xl p-5 mt-5 space-y-5"><div className="flex items-center justify-between gap-3"><h2 className="text-lg font-semibold">{createMode?"Create New File":"Edit File"}</h2>{!createMode&&<Button variant="destructive" size="sm" onClick={()=>{void remove?.();}}><Trash2 className="w-4 h-4 mr-1"/>Delete File</Button>}</div>{!createMode&&<Field label="File Number" value={app.reference_number||""} onChange={v=>setApp({...app,reference_number:v})}/>}<div className="grid sm:grid-cols-2 gap-4">{fields.map(([k,l])=><Field key={k} label={l} value={app[k]||""} onChange={v=>setApp({...app,[k]:v})}/>)}</div><div className="grid sm:grid-cols-2 gap-4"><SelectField label="Status" value={app.status||"submitted"} options={statuses} onChange={v=>setApp({...app,status:v})}/><SelectField label="Payment Status" value={app.payment_status||"unpaid"} options={payments} onChange={v=>setApp({...app,payment_status:v})}/><Field label="Payment Method" value={app.payment_method||""} onChange={v=>setApp({...app,payment_method:v})}/></div><div><label className="text-sm font-medium">Admin Notes</label><Textarea className="mt-1" value={app.admin_notes||""} onChange={e=>setApp({...app,admin_notes:e.target.value})}/></div><div><h3 className="font-semibold mb-3">Company / Employer Logo</h3><div className="border rounded-lg p-3 mb-5"><p className="text-sm font-medium mb-2">Employer Logo</p>{app.employer_logo_data?<img src={app.employer_logo_data} alt="Employer logo" className="mb-3 h-24 max-w-full object-contain rounded border"/>:<p className="text-sm text-muted-foreground mb-2">No employer logo saved</p>}<label className="inline-flex items-center gap-2 cursor-pointer"><Upload className="w-4 h-4"/><span className="text-sm">Add / Replace Employer Logo</span><input type="file" className="hidden" accept="image/*" onChange={e=>upload(app,"employer_logo_data",e.target.files?.[0])}/></label></div><h3 className="font-semibold mb-3">Documents / Images</h3><div className="grid sm:grid-cols-2 gap-4">{[["passport_copy_data","Passport Copy"],["photo_data","Applicant Photo"],["medical_cert_data","Medical Certificate"],["criminal_record_data","Criminal Record"]].map(([k,l])=><div key={k} className="border rounded-lg p-3"><p className="text-sm font-medium mb-2">{l}</p>{app[k]?<a className="text-sm underline block mb-2" href={app[k]} target="_blank" rel="noreferrer">Open Current Document</a>:<p className="text-sm text-muted-foreground mb-2">No document saved</p>}<label className="inline-flex items-center gap-2 cursor-pointer"><Upload className="w-4 h-4"/><span className="text-sm">Add / Replace</span><input type="file" className="hidden" accept="image/*,.pdf" onChange={e=>upload(app,k,e.target.files?.[0])}/></label></div>)}</div></div><div className="flex gap-2"><Button onClick={save} disabled={saving}><Save className="w-4 h-4 mr-2"/>{saving?(createMode?"Creating...":"Saving..."):(createMode?"Create File":"Save Changes")}</Button></div></div>;
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <div><label className="text-sm font-medium">{label}</label><Input className="mt-1" value={value} onChange={e=>onChange(e.target.value)}/></div>}
function SelectField({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <div><label className="text-sm font-medium">{label}</label><Select value={value} onValueChange={onChange}><SelectTrigger className="mt-1"><SelectValue/></SelectTrigger><SelectContent>{options.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div>}
function blank(){return {first_name:"",last_name:"",email:"",phone:"",nationality:"",date_of_birth:"",passport_number:"",passport_expiry:"",current_address:"",permit_type:"",job_salary:"",employer_name:"",employer_country:"",job_title:"",start_date:"",contract_duration:"",employer_logo_data:"",status:"submitted",payment_status:"unpaid",payment_method:""};}
function toPayload(a:any,create=false){return {referenceNumber:create?undefined:a.reference_number,firstName:a.first_name,lastName:a.last_name,email:a.email,phone:a.phone,nationality:a.nationality,dateOfBirth:a.date_of_birth,passportNumber:a.passport_number,passportExpiry:a.passport_expiry,currentAddress:a.current_address,permitType:a.permit_type,employerName:a.employer_name,employerCountry:a.employer_country,jobTitle:a.job_title,jobSalary:a.job_salary,startDate:a.start_date,contractDuration:a.contract_duration,hasPassport:a.has_passport,hasJobOffer:a.has_job_offer,hasMedicalCert:a.has_medical_cert,hasCriminalRecord:a.has_criminal_record,hasPhotos:a.has_photos,hasEducationCert:a.has_education_cert,passportCopyData:a.passport_copy_data,photoData:a.photo_data,medicalCertData:a.medical_cert_data,criminalRecordData:a.criminal_record_data,employerLogoData:a.employer_logo_data,status:a.status,paymentStatus:a.payment_status,paymentMethod:a.payment_method,adminNotes:a.admin_notes};}
