import { db, jobsTable } from "@workspace/db";

const jobs = [
  // ── Construction Worker (4) ──────────────────────────────────────────────
  {
    title: "Construction Worker",
    category: "Construction",
    location: "Chisinau",
    type: "Full-time",
    salary: "€1,200–€1,500/month",
    description: "Join a residential and commercial construction team in Chisinau. Tasks include bricklaying, concrete pouring, scaffolding assembly, and site clean-up. Work with experienced foremen on new-build projects throughout the capital.",
    requirements: "Physical fitness, ability to work at heights, 1+ year construction experience preferred. Basic safety certificate is a plus.",
    benefits: "Accommodation provided, transport to/from site, 28 days annual leave, PPE supplied, overtime pay available. Vacancies: 8",
  },
  {
    title: "Construction Worker",
    category: "Construction",
    location: "Balti",
    type: "Full-time",
    salary: "€1,100–€1,400/month",
    description: "Residential building contractor in Balti seeks experienced construction workers for foundation and structural work. Projects include multi-storey apartment blocks and single-family homes.",
    requirements: "Minimum 6 months hands-on construction experience. Willingness to work overtime when required.",
    benefits: "Meals provided on site, transport allowance, health insurance after probation. Vacancies: 6",
  },
  {
    title: "Construction Worker",
    category: "Construction",
    location: "Orhei",
    type: "Contract",
    salary: "€1,000–€1,300/month",
    description: "Contract construction workers needed for road and pavement renovation projects around Orhei district. Work includes excavation, laying kerb stones, and surface finishing.",
    requirements: "Valid driving licence category B preferred. Experience with hand tools and light machinery.",
    benefits: "Transport provided, safety gear included, contract renewable. Vacancies: 5",
  },
  {
    title: "Construction Worker",
    category: "Construction",
    location: "Cahul",
    type: "Seasonal",
    salary: "€950–€1,200/month",
    description: "Seasonal construction workers for summer building season in Cahul. Tasks include masonry, plastering, and general labouring on residential renovations.",
    requirements: "Basic construction knowledge. Team player with good work ethic.",
    benefits: "Shared accommodation available, meals on working days. Vacancies: 10",
  },

  // ── Warehouse Worker (4) ─────────────────────────────────────────────────
  {
    title: "Warehouse Worker",
    category: "Logistics",
    location: "Chisinau",
    type: "Full-time",
    salary: "€950–€1,150/month",
    description: "Large logistics centre near Chisinau airport requires warehouse staff for receiving, sorting, and dispatching goods. Work involves operating pallet trucks, scanning barcodes, and maintaining inventory records.",
    requirements: "Basic IT literacy, ability to lift up to 25 kg, punctual and reliable. Forklift licence a plus.",
    benefits: "Accommodation provided, meals on shift, shift allowance, uniform supplied. Vacancies: 12",
  },
  {
    title: "Warehouse Worker",
    category: "Logistics",
    location: "Balti",
    type: "Full-time",
    salary: "€900–€1,100/month",
    description: "Distribution warehouse in Balti needs pickers and packers for FMCG orders. Rotating day and night shifts available.",
    requirements: "Good numeracy, ability to stand for long periods, no experience required — training provided.",
    benefits: "Night shift bonus, transport from city centre, annual bonus scheme. Vacancies: 8",
  },
  {
    title: "Warehouse Worker",
    category: "Logistics",
    location: "Ungheni",
    type: "Full-time",
    salary: "€880–€1,050/month",
    description: "Cross-border logistics company at Ungheni customs point requires warehouse operatives to handle import/export goods. Duties include unloading trucks, quality checking, and stock counting.",
    requirements: "Russian and Romanian language skills preferred. Honest and detail-oriented.",
    benefits: "Stable hours Mon–Fri, transport provided, lunch included. Vacancies: 4",
  },
  {
    title: "Warehouse Worker",
    category: "Logistics",
    location: "Hincesti",
    type: "Full-time",
    salary: "€870–€1,000/month",
    description: "Agricultural goods warehouse near Hincesti needs seasonal and permanent workers to handle fruit, vegetables, and packaging materials.",
    requirements: "Physical stamina required. Experience with cold storage environments preferred.",
    benefits: "Accommodation on-site, meals included, retention bonus after 6 months. Vacancies: 6",
  },

  // ── Factory Worker (4) ───────────────────────────────────────────────────
  {
    title: "Factory Worker",
    category: "Manufacturing",
    location: "Chisinau",
    type: "Full-time",
    salary: "€950–€1,200/month",
    description: "Modern food processing factory in Chisinau requires production line workers. Duties include operating filling and sealing machines, quality checks, and maintaining cleanliness standards.",
    requirements: "Food hygiene certificate preferred (training provided). Ability to work rotating shifts.",
    benefits: "Health insurance, canteen meals, uniform, annual leave 28 days. Vacancies: 15",
  },
  {
    title: "Factory Worker",
    category: "Manufacturing",
    location: "Balti",
    type: "Full-time",
    salary: "€900–€1,100/month",
    description: "Electronics assembly factory seeks production workers in Balti. Tasks include component assembly, soldering, and testing finished products on the line.",
    requirements: "Good hand-eye coordination and attention to detail. Electronics experience preferred but not required.",
    benefits: "Transport provided, shift bonus, modern work environment. Vacancies: 20",
  },
  {
    title: "Factory Worker",
    category: "Manufacturing",
    location: "Soroca",
    type: "Full-time",
    salary: "€850–€1,050/month",
    description: "Textile manufacturing plant in Soroca needs production floor workers for cutting, sewing, and quality inspection of garments for European retailers.",
    requirements: "Previous factory experience preferred. Willingness to learn new machines.",
    benefits: "Accommodation available, meals on site, production bonus. Vacancies: 10",
  },
  {
    title: "Factory Worker",
    category: "Manufacturing",
    location: "Comrat",
    type: "Full-time",
    salary: "€830–€1,000/month",
    description: "Wine and beverage bottling plant in Comrat needs line operators to manage bottling, labelling, and crating of products.",
    requirements: "Physical fitness. Ability to stand for 8-hour shifts. Team-oriented attitude.",
    benefits: "Profit-sharing bonus, uniform, health check on hire. Vacancies: 8",
  },

  // ── Cleaner (3) ──────────────────────────────────────────────────────────
  {
    title: "Cleaner",
    category: "Facilities",
    location: "Chisinau",
    type: "Full-time",
    salary: "€750–€900/month",
    description: "Office and commercial cleaning company in Chisinau requires reliable cleaners for morning and evening shifts. Responsibilities include vacuuming, mopping, sanitising bathrooms, and restocking supplies.",
    requirements: "Experience in professional cleaning preferred. Trustworthy and presentable.",
    benefits: "Flexible shifts, transport allowance, equipment provided, possibility to take on additional sites. Vacancies: 10",
  },
  {
    title: "Cleaner",
    category: "Facilities",
    location: "Balti",
    type: "Part-time",
    salary: "€400–€550/month",
    description: "Shopping centre in Balti needs part-time cleaners for weekend and evening shifts. Ideal for those looking for supplementary income.",
    requirements: "No experience required. Must be available weekends.",
    benefits: "Flexible hours, uniform supplied. Vacancies: 5",
  },
  {
    title: "Cleaner",
    category: "Facilities",
    location: "Orhei",
    type: "Full-time",
    salary: "€720–€850/month",
    description: "Hospital cleaning contractor in Orhei requires full-time cleaners for clinical and non-clinical areas. COSHH awareness training provided.",
    requirements: "Attention to hygiene standards. Background check required.",
    benefits: "Stable employment, pension contribution, 28 days holiday. Vacancies: 4",
  },

  // ── Hotel Housekeeper (3) ────────────────────────────────────────────────
  {
    title: "Hotel Housekeeper",
    category: "Hospitality",
    location: "Chisinau",
    type: "Full-time",
    salary: "€850–€1,050/month",
    description: "Four-star hotel in central Chisinau seeks experienced housekeepers to maintain guest rooms and public areas to the highest standards. Responsibilities include bed making, deep cleaning, linen management, and reporting maintenance issues.",
    requirements: "Previous hotel housekeeping experience preferred. Eye for detail and pride in presentation.",
    benefits: "Meals during shift, uniform, staff discount on accommodation, tips scheme. Vacancies: 6",
  },
  {
    title: "Hotel Housekeeper",
    category: "Hospitality",
    location: "Cahul",
    type: "Full-time",
    salary: "€800–€950/month",
    description: "Resort hotel near Cahul seeks housekeeping staff for peak tourist season (May–September), with possibility of permanent contract.",
    requirements: "Good time management. Physically active. Customer service mindset.",
    benefits: "Staff accommodation, all meals provided, seasonal bonus. Vacancies: 8",
  },
  {
    title: "Hotel Housekeeper",
    category: "Hospitality",
    location: "Ungheni",
    type: "Full-time",
    salary: "€780–€920/month",
    description: "Business hotel in Ungheni needs housekeeping team members to clean and turn around guest rooms efficiently each morning.",
    requirements: "Ability to work quickly without compromising quality. Good communication.",
    benefits: "Transport allowance, staff meals, uniform provided. Vacancies: 3",
  },

  // ── Waiter/Waitress (3) ──────────────────────────────────────────────────
  {
    title: "Waiter/Waitress",
    category: "Hospitality",
    location: "Chisinau",
    type: "Full-time",
    salary: "€800–€1,100/month (incl. tips)",
    description: "Upscale restaurant in central Chisinau seeks experienced waitstaff. Responsibilities include greeting guests, taking orders, serving food and wine, and maintaining table presentation to fine-dining standards.",
    requirements: "Minimum 1 year restaurant experience. Fluency in Romanian and Russian; English a plus.",
    benefits: "Tips retained by staff, meals on shift, staff events, training in wine service. Vacancies: 4",
  },
  {
    title: "Waiter/Waitress",
    category: "Hospitality",
    location: "Balti",
    type: "Full-time",
    salary: "€700–€950/month (incl. tips)",
    description: "Popular café-restaurant in Balti city centre needs friendly and energetic waitstaff for lunch and dinner service.",
    requirements: "Customer-facing experience preferred. Positive attitude and good memory for orders.",
    benefits: "Free staff meals, tips, uniform, flexible scheduling. Vacancies: 3",
  },
  {
    title: "Waiter/Waitress",
    category: "Hospitality",
    location: "Comrat",
    type: "Part-time",
    salary: "€400–€600/month (incl. tips)",
    description: "Weekend waiter/waitress needed at a popular local restaurant in Comrat. Ideal for students or those seeking extra income.",
    requirements: "Friendly personality, basic maths for billing, reliable on weekends.",
    benefits: "Meals provided, tips, casual uniform. Vacancies: 2",
  },

  // ── Cook (3) ─────────────────────────────────────────────────────────────
  {
    title: "Cook",
    category: "Hospitality",
    location: "Chisinau",
    type: "Full-time",
    salary: "€1,000–€1,350/month",
    description: "Established restaurant group in Chisinau seeks cooks for hot and cold sections. Responsibilities include prep work, cooking to standard recipes, and maintaining food hygiene standards.",
    requirements: "Culinary qualification or 2+ years cook experience. Knowledge of European cuisine.",
    benefits: "Staff meals, tips share, career progression to sous-chef, paid training. Vacancies: 4",
  },
  {
    title: "Cook",
    category: "Hospitality",
    location: "Soroca",
    type: "Full-time",
    salary: "€900–€1,150/month",
    description: "School and corporate canteen operator in Soroca requires cooks for large-batch cooking. Menu includes traditional Moldovan and European dishes.",
    requirements: "Large-scale catering experience preferred. Valid food hygiene certificate.",
    benefits: "Stable hours (no split shifts), transport, all ingredients provided. Vacancies: 2",
  },
  {
    title: "Cook",
    category: "Hospitality",
    location: "Edinet",
    type: "Full-time",
    salary: "€850–€1,050/month",
    description: "Hotel restaurant in Edinet needs a versatile cook for breakfast, lunch, and dinner service. Opportunity to develop and update the seasonal menu.",
    requirements: "Minimum 1 year professional kitchen experience. Creativity and passion for food.",
    benefits: "Accommodation available, meals, uniform, tips share. Vacancies: 2",
  },

  // ── Kitchen Helper (3) ───────────────────────────────────────────────────
  {
    title: "Kitchen Helper",
    category: "Hospitality",
    location: "Chisinau",
    type: "Full-time",
    salary: "€650–€800/month",
    description: "Busy city-centre restaurant needs kitchen helpers to support chefs with vegetable preparation, dishwashing, and kitchen hygiene. Fast-paced environment with opportunities to learn cooking skills.",
    requirements: "No experience required — full training given. Punctual and hardworking.",
    benefits: "Staff meals, flexible shifts, pathway to cook role. Vacancies: 5",
  },
  {
    title: "Kitchen Helper",
    category: "Hospitality",
    location: "Balti",
    type: "Part-time",
    salary: "€350–€500/month",
    description: "Fast-food chain in Balti needs part-time kitchen assistants for weekend and evening shifts.",
    requirements: "Aged 18+. Ability to work in a fast-paced environment.",
    benefits: "Free meals during shifts, flexible rotas, uniform. Vacancies: 4",
  },
  {
    title: "Kitchen Helper",
    category: "Hospitality",
    location: "Cahul",
    type: "Seasonal",
    salary: "€600–€750/month",
    description: "Tourist resort near Cahul needs kitchen helpers for the summer season (June–September). Tasks include food prep, cleaning, and supporting chefs.",
    requirements: "Basic kitchen hygiene awareness. Willingness to work split shifts in summer.",
    benefits: "Accommodation and all meals included, seasonal bonus, travel back paid at end. Vacancies: 6",
  },

  // ── Delivery Driver (3) ──────────────────────────────────────────────────
  {
    title: "Delivery Driver",
    category: "Logistics",
    location: "Chisinau",
    type: "Full-time",
    salary: "€1,050–€1,300/month",
    description: "E-commerce logistics company in Chisinau needs last-mile delivery drivers with own category B licence. Route-based work, company van provided.",
    requirements: "Valid category B driving licence, minimum 2 years driving experience, clean record.",
    benefits: "Company vehicle, fuel card, mobile phone, performance bonus per delivery. Vacancies: 10",
  },
  {
    title: "Delivery Driver",
    category: "Logistics",
    location: "Balti",
    type: "Full-time",
    salary: "€950–€1,200/month",
    description: "Food and grocery delivery company in Balti requires drivers for local deliveries. Shifts available mornings and evenings.",
    requirements: "Category B licence (min. 1 year). Smart appearance. Customer-friendly attitude.",
    benefits: "Company van or moped (depending on shift), fuel, tips from customers. Vacancies: 5",
  },
  {
    title: "Delivery Driver",
    category: "Logistics",
    location: "Orhei",
    type: "Full-time",
    salary: "€900–€1,100/month",
    description: "Building materials supplier in Orhei needs drivers for inter-city deliveries. Category C licence holders preferred for heavier loads.",
    requirements: "Category B minimum; C preferred. Experience with load strapping and delivery documentation.",
    benefits: "Meal allowance, overnight accommodation for long-haul routes, stable hours. Vacancies: 3",
  },

  // ── Security Guard (3) ───────────────────────────────────────────────────
  {
    title: "Security Guard",
    category: "Security",
    location: "Chisinau",
    type: "Full-time",
    salary: "€850–€1,050/month",
    description: "Security services company in Chisinau requires uniformed guards for retail, office, and industrial site protection. 12-hour rotating shifts.",
    requirements: "Security licence (or willingness to obtain with company support). Physically fit, sober, and responsible.",
    benefits: "Uniform provided, licence training paid by company, shift allowance, health insurance. Vacancies: 15",
  },
  {
    title: "Security Guard",
    category: "Security",
    location: "Balti",
    type: "Full-time",
    salary: "€800–€980/month",
    description: "Shopping mall security team in Balti needs guards for day and night shifts. Duties include access control, CCTV monitoring, and incident reporting.",
    requirements: "Calm under pressure, good communication, valid ID card.",
    benefits: "Meals on shift, transport allowance, annual pay review. Vacancies: 6",
  },
  {
    title: "Security Guard",
    category: "Security",
    location: "Causeni",
    type: "Full-time",
    salary: "€780–€950/month",
    description: "Industrial complex near Causeni requires round-the-clock perimeter security. Guards patrol on foot and by vehicle.",
    requirements: "Previous security or military experience preferred. Driving licence desirable.",
    benefits: "Accommodation on-site, meals, uniform. Vacancies: 4",
  },

  // ── Electrician (3) ──────────────────────────────────────────────────────
  {
    title: "Electrician",
    category: "Trades",
    location: "Chisinau",
    type: "Full-time",
    salary: "€1,400–€1,800/month",
    description: "Electrical contractor in Chisinau needs qualified electricians for domestic and commercial installations, maintenance, and fault-finding. Work includes wiring, panel upgrades, and renewable energy systems.",
    requirements: "Qualified electrician (NVQ Level 3 or equivalent). Valid electrical safety certificate.",
    benefits: "Company vehicle, tool allowance, overtime at premium rate, CPD opportunities. Vacancies: 5",
  },
  {
    title: "Electrician",
    category: "Trades",
    location: "Balti",
    type: "Full-time",
    salary: "€1,300–€1,650/month",
    description: "Factory maintenance team in Balti needs an electrician for preventive and corrective maintenance on production machinery and building systems.",
    requirements: "Industrial electrical experience, PLC knowledge a plus. Commitment to safety procedures.",
    benefits: "Tool kit provided, overtime pay, skills development programme. Vacancies: 2",
  },
  {
    title: "Electrician",
    category: "Trades",
    location: "Hincesti",
    type: "Contract",
    salary: "€1,200–€1,500/month",
    description: "New housing development near Hincesti requires electricians for first and second fix wiring. Contract initially 6 months, likely to extend.",
    requirements: "Experience with residential wiring. Own hand tools required.",
    benefits: "Accommodation provided, mileage allowance, contract extensions available. Vacancies: 4",
  },

  // ── Plumber (3) ──────────────────────────────────────────────────────────
  {
    title: "Plumber",
    category: "Trades",
    location: "Chisinau",
    type: "Full-time",
    salary: "€1,300–€1,700/month",
    description: "Established plumbing and heating company in Chisinau needs qualified plumbers for domestic and commercial installations, central heating systems, and emergency call-outs.",
    requirements: "Qualified plumber with 2+ years experience. Ability to work independently and interpret technical drawings.",
    benefits: "Company van, fuel card, on-call allowance, 28 days leave. Vacancies: 4",
  },
  {
    title: "Plumber",
    category: "Trades",
    location: "Orhei",
    type: "Full-time",
    salary: "€1,150–€1,500/month",
    description: "Municipal maintenance company in Orhei needs plumbers for repair and maintenance of water supply infrastructure in public buildings and apartments.",
    requirements: "Plumbing qualification or proven apprenticeship experience. Team player.",
    benefits: "Stable government-adjacent contract, tools provided, overtime paid. Vacancies: 3",
  },
  {
    title: "Plumber",
    category: "Trades",
    location: "Soroca",
    type: "Full-time",
    salary: "€1,100–€1,400/month",
    description: "New hotel development in Soroca requires a plumber for full installation of bathroom, kitchen, and heating systems during construction phase.",
    requirements: "Experience with large-scale residential or hospitality plumbing projects.",
    benefits: "Accommodation near site, meals, contract extendable after project completion. Vacancies: 2",
  },

  // ── Welder (3) ───────────────────────────────────────────────────────────
  {
    title: "Welder",
    category: "Trades",
    location: "Chisinau",
    type: "Full-time",
    salary: "€1,200–€1,600/month",
    description: "Metal fabrication workshop in Chisinau requires skilled welders for MIG, TIG, and arc welding of structural and decorative steel components.",
    requirements: "Certified welder (MIG/TIG minimum). Ability to read technical drawings.",
    benefits: "All PPE supplied, welding certification renewal paid, overtime available. Vacancies: 4",
  },
  {
    title: "Welder",
    category: "Trades",
    location: "Balti",
    type: "Full-time",
    salary: "€1,100–€1,450/month",
    description: "Engineering company in Balti needs welders for pipeline fabrication and repair. Experience with pressure vessels and stainless steel is an advantage.",
    requirements: "MIG/MMA welding certificate. Eye test required. Physically fit.",
    benefits: "Specialist PPE, industry training, salary review after 6 months. Vacancies: 3",
  },
  {
    title: "Welder",
    category: "Trades",
    location: "Comrat",
    type: "Contract",
    salary: "€1,050–€1,350/month",
    description: "Agricultural machinery manufacturer in Comrat needs welders for production of farm equipment. Seasonal peaks in spring.",
    requirements: "Basic welding certificate. Knowledge of agricultural equipment a plus.",
    benefits: "Contract renewable, accommodation nearby, tool belt provided. Vacancies: 3",
  },

  // ── Carpenter (3) ────────────────────────────────────────────────────────
  {
    title: "Carpenter",
    category: "Trades",
    location: "Chisinau",
    type: "Full-time",
    salary: "€1,200–€1,550/month",
    description: "Joinery and fitting company in Chisinau requires carpenters for bespoke furniture making, kitchen fitting, and interior fit-out of commercial premises.",
    requirements: "Qualified carpenter or 3+ years experience. Own hand tools. Clean, precise workmanship.",
    benefits: "Van with tools, material costs covered, overtime available, portfolio projects. Vacancies: 3",
  },
  {
    title: "Carpenter",
    category: "Trades",
    location: "Edinet",
    type: "Full-time",
    salary: "€1,100–€1,400/month",
    description: "Local construction firm in Edinet needs carpenters for roof framing, formwork, and window and door installation on residential projects.",
    requirements: "Site carpentry experience. Ability to work at heights (WAH certificate preferred).",
    benefits: "Transport to site, PPE provided, 25 days annual leave. Vacancies: 4",
  },
  {
    title: "Carpenter",
    category: "Trades",
    location: "Ungheni",
    type: "Full-time",
    salary: "€1,050–€1,300/month",
    description: "Furniture manufacturing plant in Ungheni needs a production carpenter for cutting, shaping, and assembling wood components on a modern CNC-assisted line.",
    requirements: "Woodworking experience, CNC machinery knowledge preferred. Team-oriented.",
    benefits: "Production bonus, uniform, stable day shifts. Vacancies: 3",
  },

  // ── Painter (3) ──────────────────────────────────────────────────────────
  {
    title: "Painter",
    category: "Trades",
    location: "Chisinau",
    type: "Full-time",
    salary: "€1,050–€1,350/month",
    description: "Decorating company in Chisinau needs skilled painters for interior and exterior work on new-build apartments and commercial fit-outs. Work includes prep, priming, emulsion, and gloss.",
    requirements: "Minimum 2 years painting and decorating experience. Eye for straight lines and colour accuracy.",
    benefits: "All materials supplied, transport to sites, tool allowance, stable pipeline of work. Vacancies: 5",
  },
  {
    title: "Painter",
    category: "Trades",
    location: "Balti",
    type: "Full-time",
    salary: "€950–€1,200/month",
    description: "Industrial painting contractor in Balti needs painters for anti-corrosion coating of steel structures and factory floors. SSPC or NACE training provided.",
    requirements: "Industrial painting experience preferred. Willing to work in confined spaces (training available).",
    benefits: "PPE and specialist equipment provided, safety bonus, progression to supervisor. Vacancies: 4",
  },
  {
    title: "Painter",
    category: "Trades",
    location: "Hincesti",
    type: "Seasonal",
    salary: "€900–€1,100/month",
    description: "Building renovation contractor near Hincesti needs painters for exterior building refurbishment (April–October season).",
    requirements: "Experience with exterior painting, scaffold awareness training.",
    benefits: "Accommodation available, seasonal bonus, contract renewed each year. Vacancies: 6",
  },

  // ── Farm Worker (3) ──────────────────────────────────────────────────────
  {
    title: "Farm Worker",
    category: "Agriculture",
    location: "Cahul",
    type: "Seasonal",
    salary: "€800–€1,000/month",
    description: "Sunflower and corn farm near Cahul needs general farm workers for planting, cultivation, and harvest operations. Tractor and machinery operation training available.",
    requirements: "Physical fitness for outdoor work. Willing to live on or near farm during season.",
    benefits: "Accommodation provided, all meals, transport from Cahul town. Vacancies: 12",
  },
  {
    title: "Farm Worker",
    category: "Agriculture",
    location: "Comrat",
    type: "Seasonal",
    salary: "€750–€950/month",
    description: "Wine estate in Comrat region requires farm workers for vineyard maintenance: pruning, tying, and harvest. Work is outdoors in all weathers during season.",
    requirements: "Previous agricultural or vineyard experience preferred. Team-work essential.",
    benefits: "Housing in workers village, meals, end-of-harvest bonus. Vacancies: 15",
  },
  {
    title: "Farm Worker",
    category: "Agriculture",
    location: "Causeni",
    type: "Full-time",
    salary: "€820–€1,000/month",
    description: "Mixed arable and livestock farm near Causeni needs year-round farm workers. Duties cover feeding animals, crop maintenance, driving farm machinery, and general upkeep.",
    requirements: "Driving licence and tractor experience preferred. Honest and hardworking.",
    benefits: "On-farm cottage available, heating and utilities included, fresh produce allowance. Vacancies: 4",
  },

  // ── Greenhouse Worker (3) ────────────────────────────────────────────────
  {
    title: "Greenhouse Worker",
    category: "Agriculture",
    location: "Chisinau",
    type: "Full-time",
    salary: "€850–€1,050/month",
    description: "Year-round greenhouse complex near Chisinau produces tomatoes, cucumbers, and herbs for supermarkets. Workers needed for planting, training, harvesting, and packing.",
    requirements: "No experience required. Careful, patient work ethic. Ability to stand for extended periods.",
    benefits: "Transport from city, meals provided, stable year-round employment. Vacancies: 10",
  },
  {
    title: "Greenhouse Worker",
    category: "Agriculture",
    location: "Orhei",
    type: "Full-time",
    salary: "€800–€980/month",
    description: "Flower and ornamental plant greenhouse in Orhei needs workers for propagation, repotting, and care of plants for export to EU markets.",
    requirements: "Interest in horticulture. Gentle handling skills required. No allergies to plant materials.",
    benefits: "Uniform and gloves provided, health insurance, performance bonus. Vacancies: 6",
  },
  {
    title: "Greenhouse Worker",
    category: "Agriculture",
    location: "Edinet",
    type: "Seasonal",
    salary: "€780–€950/month",
    description: "Vegetable greenhouse in Edinet district needs additional staff for spring and summer growing season. Tasks include watering, pest checking, and harvesting.",
    requirements: "Seasonal availability April–September. Willingness to work early morning shifts.",
    benefits: "Accommodation on farm, meals, end-of-season bonus. Vacancies: 8",
  },

  // ── Fruit & Vegetable Picker (3) ─────────────────────────────────────────
  {
    title: "Fruit & Vegetable Picker",
    category: "Agriculture",
    location: "Cahul",
    type: "Seasonal",
    salary: "€700–€900/month",
    description: "Fruit orchards near Cahul need seasonal pickers for apples, plums, and cherries. Work runs from July to October depending on crop readiness.",
    requirements: "Physically fit. Comfortable working outdoors in summer heat. No experience required.",
    benefits: "Housing in orchard camp, three meals per day, transport to town on days off. Vacancies: 20",
  },
  {
    title: "Fruit & Vegetable Picker",
    category: "Agriculture",
    location: "Hincesti",
    type: "Seasonal",
    salary: "€650–€850/month",
    description: "Strawberry and raspberry farm near Hincesti requires pickers for June–August season. Early morning starts, with afternoons often free.",
    requirements: "Patience, gentle handling of soft fruit. Good attendance record important.",
    benefits: "Accommodation in shared rooms, all meals, transport allowance. Vacancies: 25",
  },
  {
    title: "Fruit & Vegetable Picker",
    category: "Agriculture",
    location: "Ungheni",
    type: "Seasonal",
    salary: "€680–€880/month",
    description: "Vegetable farm near Ungheni needs seasonal harvesters for tomatoes, peppers, and courgettes. Harvest season August–October.",
    requirements: "Willingness to work in outdoor conditions. Good physical stamina.",
    benefits: "On-farm accommodation, daily meals, piece-rate bonus for high output. Vacancies: 18",
  },

  // ── Caregiver (3) ────────────────────────────────────────────────────────
  {
    title: "Caregiver",
    category: "Healthcare",
    location: "Chisinau",
    type: "Full-time",
    salary: "€900–€1,100/month",
    description: "Residential care home in Chisinau seeks compassionate caregivers to support elderly residents with daily living activities including personal care, meal assistance, and social engagement.",
    requirements: "Caregiver qualification or relevant experience. Empathy, patience, and physical fitness. Clean DBS check.",
    benefits: "Funded training and qualifications, uniform, pension scheme, emotional support supervision. Vacancies: 6",
  },
  {
    title: "Caregiver",
    category: "Healthcare",
    location: "Balti",
    type: "Full-time",
    salary: "€850–€1,050/month",
    description: "Home care agency in Balti needs caregivers to support elderly and disabled clients in their own homes. Tasks include personal hygiene, medication reminders, and companionship.",
    requirements: "Driving licence desirable. Previous care experience or relevant qualification.",
    benefits: "Mileage allowance, flexible shifts, NVQ Level 2 training funded, staff support groups. Vacancies: 8",
  },
  {
    title: "Caregiver",
    category: "Healthcare",
    location: "Soroca",
    type: "Full-time",
    salary: "€820–€1,000/month",
    description: "Supported living facility in Soroca needs caregivers for adults with learning disabilities. Person-centred care approach, focus on independence and dignity.",
    requirements: "Patient, creative, and able to handle challenging behaviour. Previous SEN or care experience a plus.",
    benefits: "Accommodation near facility available, meals on shift, CPD funded. Vacancies: 4",
  },

  // ── Nurse Assistant (3) ──────────────────────────────────────────────────
  {
    title: "Nurse Assistant",
    category: "Healthcare",
    location: "Chisinau",
    type: "Full-time",
    salary: "€950–€1,200/month",
    description: "Private hospital in Chisinau requires nurse assistants to support registered nurses on medical and surgical wards. Duties include patient observations, hygiene care, and assisting with procedures.",
    requirements: "Nurse assistant diploma or equivalent. Experience in clinical settings preferred.",
    benefits: "Uniform, meals on shift, clinical training, career pathway to RN. Vacancies: 8",
  },
  {
    title: "Nurse Assistant",
    category: "Healthcare",
    location: "Balti",
    type: "Full-time",
    salary: "€900–€1,100/month",
    description: "District hospital in Balti needs nurse assistants for long-term patient wards. Role supports patients with mobility, feeding, and comfort needs.",
    requirements: "Nurse assistant qualification (or completing final year of training). Good team communication.",
    benefits: "Government employment stability, professional registration support, CPD days. Vacancies: 6",
  },
  {
    title: "Nurse Assistant",
    category: "Healthcare",
    location: "Edinet",
    type: "Full-time",
    salary: "€860–€1,050/month",
    description: "Medical centre in Edinet seeks nurse assistants for outpatient and day surgery support. Flexible rotating shift patterns.",
    requirements: "Medical background required. Comfortable with clinical environment.",
    benefits: "Transport allowance, medical insurance, uniform, shift supplements. Vacancies: 3",
  },

  // ── Receptionist (3) ─────────────────────────────────────────────────────
  {
    title: "Receptionist",
    category: "Administration",
    location: "Chisinau",
    type: "Full-time",
    salary: "€800–€1,000/month",
    description: "Corporate office building in Chisinau needs a professional receptionist to manage visitor registration, switchboard, post, and meeting room bookings. First point of contact for clients.",
    requirements: "Professional appearance, fluent Romanian and Russian, English desirable. Proficient in MS Office.",
    benefits: "Smart uniform, annual leave 25 days, career development, staff benefits scheme. Vacancies: 2",
  },
  {
    title: "Receptionist",
    category: "Administration",
    location: "Balti",
    type: "Full-time",
    salary: "€750–€950/month",
    description: "Medical clinic in Balti needs a receptionist to handle patient appointments, enquiries, and administration. Calm and professional manner essential.",
    requirements: "Good organisational skills, experience with booking systems, medical reception a plus.",
    benefits: "Private medical cover, stable hours Mon–Sat, paid lunch break, friendly team. Vacancies: 1",
  },
  {
    title: "Receptionist",
    category: "Administration",
    location: "Orhei",
    type: "Full-time",
    salary: "€720–€900/month",
    description: "Hotel in Orhei needs a receptionist for check-in/check-out, telephone enquiries, and concierge services. Evening and weekend availability required.",
    requirements: "Hotel reception or customer service experience. Confident telephone manner.",
    benefits: "Staff accommodation discount, shift meal, uniform, tips from satisfied guests. Vacancies: 2",
  },

  // ── Office Assistant (3) ─────────────────────────────────────────────────
  {
    title: "Office Assistant",
    category: "Administration",
    location: "Chisinau",
    type: "Full-time",
    salary: "€750–€950/month",
    description: "International trading company in Chisinau needs an office assistant for document management, data entry, filing, and general administrative support across departments.",
    requirements: "Computer literacy (MS Office), attention to detail, organised, good written communication.",
    benefits: "Modern office environment, career growth, training, team lunches, annual bonus. Vacancies: 3",
  },
  {
    title: "Office Assistant",
    category: "Administration",
    location: "Causeni",
    type: "Full-time",
    salary: "€700–€850/month",
    description: "Local government office in Causeni needs an administrative assistant to process applications, manage correspondence, and support department managers.",
    requirements: "Previous administrative experience. Fluent Romanian. Honest and discreet.",
    benefits: "Public sector employment, stable hours, pension scheme, 28 days leave. Vacancies: 1",
  },
  {
    title: "Office Assistant",
    category: "Administration",
    location: "Ungheni",
    type: "Part-time",
    salary: "€400–€550/month",
    description: "Small logistics firm in Ungheni needs a part-time office assistant (20 hours/week) for invoicing, phone calls, and basic bookkeeping support.",
    requirements: "Basic accounting knowledge. Proficient in spreadsheets. Reliable.",
    benefits: "Flexible hours (mornings), friendly small team, potential to go full-time. Vacancies: 1",
  },

  // ── Sales Assistant (3) ──────────────────────────────────────────────────
  {
    title: "Sales Assistant",
    category: "Retail",
    location: "Chisinau",
    type: "Full-time",
    salary: "€750–€1,000/month (base + commission)",
    description: "Electronics and appliance retailer in a Chisinau shopping mall needs sales assistants to advise customers, demonstrate products, and close sales. Commission structure rewards performance.",
    requirements: "Good communication and persuasion skills. Product knowledge training provided.",
    benefits: "Commission on top of base salary, staff discount, target bonus, career into team leader. Vacancies: 4",
  },
  {
    title: "Sales Assistant",
    category: "Retail",
    location: "Balti",
    type: "Full-time",
    salary: "€700–€900/month",
    description: "Fashion clothing store in Balti city centre needs sales assistants for customer service, stock replenishment, and visual merchandising.",
    requirements: "Friendly, fashion-conscious, good on your feet all day. Previous retail experience preferred.",
    benefits: "Staff clothing allowance, target bonus, flexible shifts. Vacancies: 3",
  },
  {
    title: "Sales Assistant",
    category: "Retail",
    location: "Comrat",
    type: "Part-time",
    salary: "€380–€550/month",
    description: "Mobile phone and accessories shop in Comrat needs a part-time sales assistant for afternoons and weekends.",
    requirements: "Interest in technology, honest, numerate, customer-oriented.",
    benefits: "Staff SIM deal, product training, potential for full-time role. Vacancies: 1",
  },

  // ── Cashier (3) ──────────────────────────────────────────────────────────
  {
    title: "Cashier",
    category: "Retail",
    location: "Chisinau",
    type: "Full-time",
    salary: "€720–€880/month",
    description: "Busy supermarket chain in Chisinau needs cashiers to operate checkout tills, handle cash and card payments accurately, and maintain a friendly customer experience.",
    requirements: "Numeracy skills, reliable, customer-facing manner. Previous cashier experience a plus.",
    benefits: "Staff discount card, uniform, 25 days leave, opportunity for supervisor promotion. Vacancies: 8",
  },
  {
    title: "Cashier",
    category: "Retail",
    location: "Balti",
    type: "Full-time",
    salary: "€680–€850/month",
    description: "Home improvement store in Balti requires cashiers for checkout and returns desk. Includes operating lottery and bill-pay services.",
    requirements: "Basic IT, cash handling experience, trustworthy and presentable.",
    benefits: "Stable hours, uniform, staff discount, annual bonus. Vacancies: 3",
  },
  {
    title: "Cashier",
    category: "Retail",
    location: "Orhei",
    type: "Part-time",
    salary: "€380–€520/month",
    description: "Small grocery store in Orhei town centre needs a part-time cashier for afternoon and Saturday shifts.",
    requirements: "Aged 18+, reliable, honest. No experience needed — full training.",
    benefits: "Flexible shifts, uniform, free snacks, may become full-time. Vacancies: 2",
  },

  // ── Supermarket Staff (3) ────────────────────────────────────────────────
  {
    title: "Supermarket Staff",
    category: "Retail",
    location: "Chisinau",
    type: "Full-time",
    salary: "€750–€920/month",
    description: "Major supermarket chain in Chisinau needs general store staff for shelf-stacking, customer service, produce departments, and stock rotation. Night and day shifts available.",
    requirements: "Reliable, physically active, good team player. No experience necessary.",
    benefits: "Staff discount, uniform, structured shift patterns, overtime available. Vacancies: 20",
  },
  {
    title: "Supermarket Staff",
    category: "Retail",
    location: "Soroca",
    type: "Full-time",
    salary: "€700–€880/month",
    description: "Regional supermarket in Soroca needs floor staff for fresh produce and chilled sections. Early morning starts (5am–1pm).",
    requirements: "Punctual, physically fit. Previous retail or food handling experience preferred.",
    benefits: "Transport supplement for early shifts, meals, 25 days holiday. Vacancies: 6",
  },
  {
    title: "Supermarket Staff",
    category: "Retail",
    location: "Edinet",
    type: "Full-time",
    salary: "€680–€850/month",
    description: "New supermarket opening in Edinet — all positions available from shelf fillers to department supervisors. Exceptional candidates may be fast-tracked to team leader roles.",
    requirements: "Motivated, customer-friendly, willing to work rotating shifts.",
    benefits: "Opening bonus, staff discount, uniform, comprehensive induction training. Vacancies: 15",
  },

  // ── Packaging Worker (3) ─────────────────────────────────────────────────
  {
    title: "Packaging Worker",
    category: "Manufacturing",
    location: "Chisinau",
    type: "Full-time",
    salary: "€850–€1,050/month",
    description: "Cosmetics manufacturer in Chisinau needs packaging operatives to fill, label, and pack beauty products on a semi-automated line. Clean room conditions apply.",
    requirements: "Attention to detail, hygiene-conscious. Experience in FMCG packaging preferred.",
    benefits: "Clean working environment, uniform, annual bonus, canteen on site. Vacancies: 10",
  },
  {
    title: "Packaging Worker",
    category: "Manufacturing",
    location: "Balti",
    type: "Full-time",
    salary: "€800–€1,000/month",
    description: "Food manufacturer in Balti needs packagers to weigh, fill, seal, and box products for retail distribution. QC checks at each stage.",
    requirements: "Good dexterity, ability to keep pace with production targets, reliable attendance.",
    benefits: "Shift bonus, transport, meals, development into quality controller role. Vacancies: 8",
  },
  {
    title: "Packaging Worker",
    category: "Manufacturing",
    location: "Cahul",
    type: "Seasonal",
    salary: "€750–€950/month",
    description: "Agricultural produce company in Cahul needs seasonal packaging staff for fresh fruit and vegetable packing during harvest season (July–October).",
    requirements: "No experience necessary. Fast and careful hands. Good hygiene standards.",
    benefits: "Accommodation in packing house village, meals, piece-rate bonus. Vacancies: 20",
  },

  // ── Machine Operator (3) ─────────────────────────────────────────────────
  {
    title: "Machine Operator",
    category: "Manufacturing",
    location: "Chisinau",
    type: "Full-time",
    salary: "€1,000–€1,300/month",
    description: "Printing and packaging company in Chisinau needs machine operators for offset and digital printing lines. Setting, running, and cleaning print machines.",
    requirements: "Previous machine operation experience. Good colour vision. Ability to work to tight deadlines.",
    benefits: "Shift bonus, technical training, career path to machine setter. Vacancies: 5",
  },
  {
    title: "Machine Operator",
    category: "Manufacturing",
    location: "Balti",
    type: "Full-time",
    salary: "€950–€1,200/month",
    description: "Plastics factory in Balti requires injection moulding machine operators. Tasks include setting up moulds, monitoring production, and quality checking output.",
    requirements: "Injection moulding or relevant manufacturing experience preferred.",
    benefits: "Day and night shifts available, shift premium, tool kit, production bonus. Vacancies: 6",
  },
  {
    title: "Machine Operator",
    category: "Manufacturing",
    location: "Soroca",
    type: "Full-time",
    salary: "€900–€1,100/month",
    description: "Wood processing mill in Soroca needs machine operators for sawing, planing, and profiling timber. Experience with CNC woodworking machines desirable.",
    requirements: "Machine operation experience, safety awareness, physically active.",
    benefits: "Safety gear provided, stable employment, transport allowance. Vacancies: 4",
  },

  // ── Textile Worker (3) ───────────────────────────────────────────────────
  {
    title: "Textile Worker",
    category: "Manufacturing",
    location: "Balti",
    type: "Full-time",
    salary: "€780–€980/month",
    description: "Garment factory in Balti producing clothing for European brands needs textile workers for cutting, sewing, and quality control. Work to international quality standards.",
    requirements: "Sewing machine experience preferred. Good manual dexterity. Attention to finish quality.",
    benefits: "Production bonus, transport, canteen, staff shop discount. Vacancies: 25",
  },
  {
    title: "Textile Worker",
    category: "Manufacturing",
    location: "Chisinau",
    type: "Full-time",
    salary: "€820–€1,020/month",
    description: "Fashion sample room in Chisinau needs skilled sewers for prototype and small-run production of designer garments. Work closely with design team.",
    requirements: "Industrial sewing machine operation. Pattern reading skills. High attention to detail.",
    benefits: "Modern studio environment, staff discount on garments, creative team culture. Vacancies: 6",
  },
  {
    title: "Textile Worker",
    category: "Manufacturing",
    location: "Soroca",
    type: "Full-time",
    salary: "€760–€950/month",
    description: "Curtain and upholstery fabric factory in Soroca needs textile workers for weaving, dyeing, and finishing operations.",
    requirements: "Previous textile or weaving experience preferred. Colour awareness important.",
    benefits: "Transport provided, healthy canteen, uniform, stable employment. Vacancies: 10",
  },

  // ── Laundry Worker (3) ───────────────────────────────────────────────────
  {
    title: "Laundry Worker",
    category: "Facilities",
    location: "Chisinau",
    type: "Full-time",
    salary: "€720–€900/month",
    description: "Commercial laundry supplying hotels and hospitals in Chisinau needs workers for washing, drying, pressing, and packing linen. Hot, physically demanding environment.",
    requirements: "Ability to work in warm conditions. Physical stamina for lifting and folding. Reliable attendance.",
    benefits: "Uniform provided, transport, regular hours Mon–Fri. Vacancies: 6",
  },
  {
    title: "Laundry Worker",
    category: "Facilities",
    location: "Balti",
    type: "Full-time",
    salary: "€680–€850/month",
    description: "Hotel chain laundry facility in Balti needs workers for linen and uniform processing. Early morning and day shifts.",
    requirements: "No experience needed — full training. Team player, good pace of work.",
    benefits: "Meals on shift, transport, staff events, year-round stable work. Vacancies: 4",
  },
  {
    title: "Laundry Worker",
    category: "Facilities",
    location: "Orhei",
    type: "Part-time",
    salary: "€380–€520/month",
    description: "Small laundry and dry-cleaning shop in Orhei needs a part-time worker for customer intake, sorting, pressing, and handover.",
    requirements: "Customer-friendly, careful with delicate items, basic ironing skills.",
    benefits: "Flexible part-time hours, small friendly team, tips from happy customers. Vacancies: 1",
  },

  // ── General Labourer (3) ─────────────────────────────────────────────────
  {
    title: "General Labourer",
    category: "Construction",
    location: "Chisinau",
    type: "Full-time",
    salary: "€900–€1,100/month",
    description: "Construction contractor in Chisinau needs general labourers to support skilled trades with material handling, site clean-up, scaffolding assist, and rubbish removal.",
    requirements: "Physically fit, willing to learn, punctual. No experience required — on-site training given.",
    benefits: "Transport to site, PPE provided, opportunity to train in skilled trade, overtime available. Vacancies: 15",
  },
  {
    title: "General Labourer",
    category: "Construction",
    location: "Orhei",
    type: "Contract",
    salary: "€850–€1,050/month",
    description: "Roadworks contractor near Orhei needs general labourers for road resurfacing project. Tasks include traffic management, flagging, and materials handling.",
    requirements: "Road construction experience preferred. Traffic management awareness. Outdoor work in all seasons.",
    benefits: "Contract until project completion (~6 months), accommodation near site, meals. Vacancies: 8",
  },
  {
    title: "General Labourer",
    category: "Construction",
    location: "Causeni",
    type: "Seasonal",
    salary: "€800–€1,000/month",
    description: "Irrigation infrastructure project near Causeni needs general labourers for digging, pipe laying, and back-filling. Seasonal work April–October.",
    requirements: "Manual work experience. Comfortable working outdoors. Team player.",
    benefits: "Accommodation in local village, meals, end-of-project bonus. Vacancies: 10",
  },
];

async function main() {
  console.log(`Inserting ${jobs.length} new job listings (skipping duplicate check)…`);
  const inserted = await db.insert(jobsTable).values(jobs).returning({ id: jobsTable.id, title: jobsTable.title });
  console.log(`✅ Inserted ${inserted.length} jobs successfully.`);
  inserted.slice(0, 5).forEach(j => console.log(`  → [${j.id}] ${j.title}`));
  if (inserted.length > 5) console.log(`  … and ${inserted.length - 5} more`);
  process.exit(0);
}

main().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
